### PR TITLE
fix: modify unsubscribe cleanup routine and tests

### LINKED ISSUE #79: eth_getFilterChanges occasionally returns JNull on Windows
On Windows when running tests, occasionally tests were failing with the following error:

```
`node.kind == JArray` : items() can not iterate a JsonNode of kind JNull"
```

the error is caused by `eth_getFilterChanges` occasionally returning `JNull` instead of `JArray` on Windows.

This is happening in [vendor/nim-ethers/ethers/providers/jsonrpc/subscriptions.nim](https://github.com/codex-storage/nim-ethers/blob/e15974eb1f0ef3b7ed50b6f6529244d6047229d0/ethers/providers/jsonrpc/subscriptions.nim#L148):

```nim
proc getChanges(id: JsonNode): Future[JsonNode] {.async.} =
  try:
    return await subscriptions.client.eth_getFilterChanges(id)
  except CatchableError:
    return newJArray()

proc poll(id: JsonNode) {.async.} =
  for change in await getChanges(id):
    if callback =? subscriptions.getCallback(id):
      callback(id, change)
```

The code is basically correct, as _should_ always return a `JArray`. A fix could e.g.:

```nim
proc poll(id: JsonNode) {.async.} =
  let changes = await getChanges(id)
  if changes.kind != JArray:
    return
  for change in changes:
    if callback =? subscriptions.getCallback(id):
      callback(id, change)
```

Alternatively, we could also modify the `getChanges` proc.

A similar issue were reported in the past for go-ethereum: https://github.com/ethereum/go-ethereum/issues/2746, but it should be resolved by now. Maybe somehow it propagated to HardHat and apparently on Windows only - I could not find any issue at Hardhat's GitHub.

### PR DESCRIPTION
**Pull request by emizzle**
Closes #79 

Modifying the cleanup:
- Ignore exceptions (other than CancelledError) if uninstallation of the filter fails. If it's the last step in the subscription cleanup, then filter changes for this filter will no longer be polled so if the filter continues to live on in geth for whatever reason, then it doesn't matter.

To fix the subscription filter tests:
- `CancelledError` is now caught inside of `getChanges`. This was causing conditions during `subscriptions.close`, where the `CancelledError` would get consumed by the `except CatchableError`, if there was an ongoing `poll` happening at the time of close.
- After creating a new filter inside of `getChanges`, the new filter is polled for changes before returning.
- `getChanges` also does not swallow `CatchableError` by returning an empty array, and instead re-raises the error if it is not `filter not found`.
- #79 was fixed by checking the return value of `eth_getFilterChanges`. If `JNull` was received, then an empty array is returned.
- The tests were simplified by accessing the private fields of `PollingSubscriptions`. That way, there wasn't a race condition for the `newFilterId` counter inside of the mock.
- The `MockRpcHttpServer` was simplified by keeping track of the active filters only, and invalidation simply removes the filter. The tests then only needed to rely on the fact that the filter id changed in the mapping.
- Because of the above changes, we no longer needed to sleep inside of the tests, so the sleeps were removed, and the polling interval could be changed to 1ms, which not only makes the tests faster, but would further highlight any race conditions if present.

Co-authored-by: Adam Uhlíř <adam@uhlir.dev>

### CODE REVIEW

File: ethers/providers/jsonrpc/subscriptions.nim [hunk 1]
```diff
@@ -151,14 +152,24 @@ proc new*(_: type JsonRpcSubscriptions,
...
+      let changes = await subscriptions.client.eth_getFilterChanges(mappedId)
+      if changes.kind == JNull:
+        return newJArray()
+      elif changes.kind != JArray:
+        raise newException(SubscriptionError,
+          "HTTP polling: unexpected value returned from eth_getFilterChanges." &
+          " Expected: JArray, got: " & $changes.kind)
+      return changes
+    except CancelledError as e:
+      raise e
```
Comment (AuHau) [inline ethers/providers/jsonrpc/subscriptions.nim:164]: I would not raise inside polling loop, but we have planned the Result approach so I will pick that up based on this work.

File: ethers/providers/jsonrpc/subscriptions.nim [hunk 2]
```diff
@@ -151,14 +152,24 @@ proc new*(_: type JsonRpcSubscriptions,
...
     except CatchableError as e:
       if "filter not found" in e.msg:
         let filter = subscriptions.filters[originalId]
         let newId = await subscriptions.client.eth_newFilter(filter)
         subscriptions.subscriptionMapping[originalId] = newId
```
Comment (AuHau) [inline ethers/providers/jsonrpc/subscriptions.nim:169]: Btw. we are leaving a place for race condition here. While its probability is small, it can still happen. The `await` here yields the processing of this, so if meanwhile for example `unsubscribe` is called, then it will use the old ID because the new one was not yet processed. I will leave up to you if you want to mitigate that or will leave it as is.

File: testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim [hunk 3]
```diff
@@ -122,35 +128,26 @@ suite "HTTP polling subscriptions - filter not found":
...
-    let jsonId = await subscriptions.subscribeLogs(filter, emptyHandler)
-    let id = string.fromJson(jsonId).tryGet
-    check mockServer.newFilterCounter == 1
+    check subscriptions.filters.len == 0
+    check subscriptions.subscriptionMapping.len == 0
+
+    let id = await subscriptions.subscribeLogs(filter, emptyHandler)
+
+    check subscriptions.filters[id] == filter
+    check subscriptions.subscriptionMapping[id] == id
```
Comment (AuHau) [inline testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim:137]: Maybe add check that `len == 1`?

**Review by AuHau — APPROVED** [review]
Few comments that I will leave up to you, but otherwise LGTM

File: testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim (hunk 3 above)
Comment (emizzle) [reply testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim:137]: Updated.

File: ethers/providers/jsonrpc/subscriptions.nim (hunk 2 above)
Comment (emizzle) [reply ethers/providers/jsonrpc/subscriptions.nim:169]: To be addressed in https://github.com/codex-storage/nim-ethers/issues/86.
